Reference OTL: Die drei Hexen Hoi, Sinek Marko, bu'scht Du haint geschlufn?
Reference ARE: Europa, Suedosteuropa, Jugoslavija, Gottschee
Reference YOR: 4, S. 224
Comment	   ????
Reference SCT: Q0080B
Reference YEM: Copyright 1995, estate of Helmut Schaffrath.
Info keysig 1 sharp
Info key G Major
Note	0	1000	67
Note	1000	2000	71
Note	2000	3000	69
Note	3000	4000	67
Note	4000	6000	74
Note	6000	6500	69
Note	6500	7000	71
Note	7000	8000	72
Note	8000	9000	71
Note	9000	10000	69
Note	10000	11000	67
Reference AGN: Ballade, Magie, Verwuenschung
Reference ONB: ESAC (Essen Associative Code) Database: BALLADE
Reference AMT: simple triple
Reference AIN: vox
Reference EED: Helmut Schaffrath
Reference EEV: 1.0
