Reference OTL: Der Benzenauer
Reference ARE: Europa, Mitteleuropa, Deutschland
Reference SCT: A0381C
Reference YEM: Copyright 1995, estate of Helmut Schaffrath.
Comment	Mixed meters:  4/2; 6/2
Info keysig 1 sharp
Info key F Major
Note	0	2000	77
Note	1000	3000	76
Note	2000	4000	74
Note	3000	5000	76
Note	4000	6000	72
Note	5000	9000	69
Note	7000	11000	65
Note	9000	13000	72
Note	11000	15000	74
Note	13000	19000	72
Note	16000	18000	69
Note	17000	21000	70
Note	19000	27000	67
Note	23000	29000	65
Reference AGN: Romanze, Ballade, Lied, Personenlied
Comment	Fragment bei Schmeltzel 1544 No. 6
Reference ONB: ESAC (Essen Associative Code) Database: ALTDEU
Reference AMT: irregular
Reference AIN: vox
Reference EED: Helmut Schaffrath
Reference EEV: 1.0
