Reference OTL: Entfuehrung unterm Tanz Bie vrie ischt auf nar Knes'n Jure.
Reference ARE: Europa, Suedosteuropa, Jugoslavija, Gottschee, Oberpockstein
Reference YOR: 5, S. 48
Comment	   1907 aufgezeichnet
Reference SCT: Q0092
Reference YEM: Copyright 1995, estate of Helmut Schaffrath.
Info keysig no accidentals
Info key A Minor
Note	0	500	69
Note	500	1000	69
Note	1000	1500	72
Note	1500	2500	74
Note	2500	3500	74
Note	3500	4000	72
Note	4000	4500	71
Note	4500	5500	72
Note	5500	6000	69
Reference AGN: Ballade, Entfuehrung
Reference ONB: ESAC (Essen Associative Code) Database: BALLADE
Reference AMT: simple triple
Reference AIN: vox
Reference EED: Helmut Schaffrath
Reference EEV: 1.0
